### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by shefali163**

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@shefali163 what is this PR for?

**Comment by VibhorCodecianGupta** [comment]
@shefali163 could you please redo this one? Not just the tests, the main APIs need to be promisified too. The entire codebase needs revamping. Also, while using arrow functions, try to write the callback in a single line. The beauty of fat arrows is the shorthand itself

**Comment by shefali163** [comment]
could you please tell exactly which files needs to be promisified becoz i
already did the main api's in utils folder

**Comment by vibhorgupta-gh** [comment]
@shefali163 my bad, some files some files were not showing the entire diff because of a lot of changes. You've made the changes everywhere, good work. Just resolve the conflicts and we're good to merge

**Comment by vibhorgupta-gh** [comment]
I think your google login commits are also included here. While resolving conflicts, make sure you  discard your changes and keep the ones already merged by me before @shefali163 (for google login, that is)

**Comment by shefali163** [comment]
ohkay! i guess the "conflicts" we are talking about is the correct use of
arrow functions. right?

**Comment by vibhorgupta-gh** [comment]
@shefali163 you must be seeing a list of files here which have conflicts. thats because i merged some code after you submitted this PR. There are a lot of sections where your code and my code are inconsistent, just fix those. pull my develop into your editor and you'll see the conflicts

**Pull request merged**
