### PR TITLE
adding routes and waiting for schemas

### PR DESCRIPTION
**Pull request by zephyr007**

### CODE REVIEW

**Comment by zephyr007** [comment]
I have removed that file

**Comment by thegauravtiwari** [comment]
Squash your commits into one commit.

**Comment by zephyr007** [comment]
I resolved the conflict

**Comment by VibhorCodecianGupta** [comment]
This task wasn't assigned to you. Please do the tasks assigned to you.

**Comment by zephyr007** [comment]
you assigned me this

**Comment by VibhorCodecianGupta** [comment]
Read the conversation on whatsapp again. I assigned Sparsh the task of schemas, and Pratyush the task of routing. You and Shivang will make the APIs once this is done. Take special care of all this. I'll be assigning tasks on issues now to avoid confusion.

**Comment by VibhorCodecianGupta** [comment]
Pratyush is already making the routes.

**Pull request closed without merging**
